# Generated by Django 4.0.4 on 2022-05-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
