# Generated by Django 4.0.4 on 2022-05-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='about',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_details',
            field=models.TextField(verbose_name='Details'),
        ),
    ]
