# Generated by Django 4.0.4 on 2022-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_settings_facebook_remove_settings_youtube_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='settings',
            name='tiktok',
            field=models.CharField(max_length=255, verbose_name='@Tiktok'),
        ),
    ]
