# Generated by Django 4.0.4 on 2022-05-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_teacher_facebook_remove_teacher_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_details',
            field=models.TextField(default='0', verbose_name='Details'),
        ),
    ]
