# Generated by Django 4.0.4 on 2022-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_course_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseType',
            field=models.CharField(default='0', max_length=255, verbose_name='CourseType'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='1', max_length=255, verbose_name='Course Duration'),
        ),
    ]
